import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import localFont from "next/font/local";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "sonner";

const apparel = localFont({
  src: "./apparel.otf",
  variable: "--font-apparel",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${apparel.variable} antialiased grid grid-rows-[1fr_auto] min-h-screen font-sans`}
        >
          <QueryProvider>{children}</QueryProvider>
          <div className="fixed">
            <Toaster />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
